# Generated by Django 2.1.4 on 2019-03-04 09:24

import cms.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default=1, max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('en_titulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Título')),
                ('subtitulo', models.CharField(blank=True, max_length=100, verbose_name='Subtítulo')),
                ('en_subtitulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Subtítulo')),
                ('informacion', models.TextField(blank=True, verbose_name='Información')),
                ('en_informacion', models.TextField(blank=True, default='', verbose_name='En Información')),
                ('prioridad', models.IntegerField(blank=True, default=0, verbose_name='Prioridad')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color')),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='cms.Categoria', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default=1, max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('en_titulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Título')),
                ('subtitulo', models.CharField(blank=True, max_length=100, verbose_name='Subtítulo')),
                ('en_subtitulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Subtítulo')),
                ('informacion', models.TextField(blank=True, verbose_name='Información')),
                ('en_informacion', models.TextField(blank=True, default='', verbose_name='En Información')),
                ('prioridad', models.IntegerField(blank=True, default=0, verbose_name='Prioridad')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='photos/default.jpg', upload_to='photos', verbose_name='Imagen')),
                ('object_id', models.PositiveIntegerField(default=1, verbose_name='Objeto')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_image', to='contenttypes.ContentType', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default=1, max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('en_titulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Título')),
                ('subtitulo', models.CharField(blank=True, max_length=100, verbose_name='Subtítulo')),
                ('en_subtitulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Subtítulo')),
                ('informacion', models.TextField(blank=True, verbose_name='Información')),
                ('en_informacion', models.TextField(blank=True, default='', verbose_name='En Información')),
                ('prioridad', models.IntegerField(blank=True, default=0, verbose_name='Prioridad')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('puntuacion', cms.models.IntegerRangeField(blank=True, null=True, verbose_name='Puntuación')),
                ('destacado', models.BooleanField(blank=True, default=False, verbose_name='Destacado')),
                ('servicios', models.TextField(blank=True, default='', verbose_name='Servicios')),
                ('en_servicios', models.TextField(blank=True, default='', verbose_name='En Servicios')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('telefono1', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono 2')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Pagina Web')),
                ('reserva', models.URLField(blank=True, null=True, verbose_name='Reservar')),
                ('compra', models.URLField(blank=True, null=True, verbose_name='Comprar')),
                ('vista360', models.URLField(blank=True, null=True, verbose_name='Vista 360')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_category', to='cms.Categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default=1, max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('en_titulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Título')),
                ('subtitulo', models.CharField(blank=True, max_length=100, verbose_name='Subtítulo')),
                ('en_subtitulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Subtítulo')),
                ('informacion', models.TextField(blank=True, verbose_name='Información')),
                ('en_informacion', models.TextField(blank=True, default='', verbose_name='En Información')),
                ('prioridad', models.IntegerField(blank=True, default=0, verbose_name='Prioridad')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_place', to='cms.Lugar', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default=1, max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('en_titulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Título')),
                ('subtitulo', models.CharField(blank=True, max_length=100, verbose_name='Subtítulo')),
                ('en_subtitulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Subtítulo')),
                ('informacion', models.TextField(blank=True, verbose_name='Información')),
                ('en_informacion', models.TextField(blank=True, default='', verbose_name='En Información')),
                ('prioridad', models.IntegerField(blank=True, default=0, verbose_name='Prioridad')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_place', to='cms.Lugar', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default=1, max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('en_titulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Título')),
                ('subtitulo', models.CharField(blank=True, max_length=100, verbose_name='Subtítulo')),
                ('en_subtitulo', models.CharField(blank=True, default='', max_length=100, verbose_name='En Subtítulo')),
                ('informacion', models.TextField(blank=True, verbose_name='Información')),
                ('en_informacion', models.TextField(blank=True, default='', verbose_name='En Información')),
                ('prioridad', models.IntegerField(blank=True, default=0, verbose_name='Prioridad')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('tipo', models.CharField(choices=[('Noticia', 'Noticia'), ('Evento', 'Evento')], default=1, max_length=20, verbose_name='Tipo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_category', to='cms.Categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('video', embed_video.fields.EmbedVideoField(verbose_name='Video Url')),
                ('object_id', models.PositiveIntegerField(default=1, verbose_name='Objeto')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_video', to='contenttypes.ContentType', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_place', to='cms.Lugar', verbose_name='Lugar'),
        ),
    ]
