# Generated by Django 2.1.4 on 2019-04-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='telefono1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono 1'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='telefono2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono 2'),
        ),
    ]
