# Generated by Django 2.1.4 on 2019-03-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='titulo',
            field=models.CharField(default='', max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
