# Generated by Django 2.1.4 on 2019-03-04 19:06

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_imagen_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='', verbose_name='Video Url'),
            preserve_default=False,
        ),
    ]
