# Generated by Django 2.1.4 on 2019-03-04 19:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20190304_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='en_informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=1, max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='en_informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=1, max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='en_informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=1, max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='en_informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=1, max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='en_informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=1, max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='en_informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=1, max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Información'),
        ),
    ]
