# Generated by Django 2.1.4 on 2019-03-04 19:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20190304_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='en_informacion',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='informacion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='en_informacion',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='informacion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='en_informacion',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='informacion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='en_informacion',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='informacion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='en_informacion',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='informacion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='en_informacion',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='En Información'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='informacion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Información'),
        ),
    ]
