# Generated by Django 2.1.4 on 2019-03-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20190304_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Longitud'),
        ),
    ]
