# Generated by Django 2.1.4 on 2019-03-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20190316_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='latitud',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitud'),
        ),
    ]
