# Generated by Django 2.1.4 on 2019-03-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20190316_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_category', to='cms.Categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitud'),
        ),
    ]
