# Generated by Django 2.1.4 on 2019-03-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20190316_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_place', to='cms.Lugar', verbose_name='Lugar'),
        ),
    ]
