# Generated by Django 2.1.4 on 2019-03-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20190317_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_place', to='cms.Lugar', verbose_name='Lugar'),
        ),
    ]
