# Generated by Django 2.1.4 on 2019-03-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20190317_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Cantidad'),
        ),
    ]
