# Generated by Django 2.1.4 on 2019-03-17 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20190317_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_place', to='cms.Lugar', verbose_name='Lugar'),
        ),
    ]
