# Generated by Django 2.1.4 on 2019-03-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20190318_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodohorario',
            name='horario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='periods_schedule', to='cms.Horario', verbose_name='Horario'),
            preserve_default=False,
        ),
    ]
