# Generated by Django 2.1.4 on 2019-03-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_periodohorario_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=9, verbose_name='Nombre')),
                ('horario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_day', to='cms.Horario', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Periodo Horario',
                'verbose_name_plural': 'Periodos Horario',
            },
        ),
        migrations.AlterModelOptions(
            name='periodohorario',
            options={'verbose_name': 'Periodo Horario', 'verbose_name_plural': 'Periodos Horario'},
        ),
        migrations.RemoveField(
            model_name='periodohorario',
            name='horario',
        ),
        migrations.AlterField(
            model_name='periodohorario',
            name='dia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.DiaHorario', verbose_name='Día'),
        ),
    ]
