# Generated by Django 2.1.4 on 2019-03-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20190318_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diahorario',
            options={'verbose_name': 'Día Horario', 'verbose_name_plural': 'Días Horario'},
        ),
    ]
