# Generated by Django 2.1.4 on 2019-03-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20190319_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diahorario',
            name='horario',
        ),
        migrations.AddField(
            model_name='periodohorario',
            name='horario',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_day', to='cms.Horario', verbose_name='Horario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodohorario',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default=1, max_length=9, verbose_name='Día'),
        ),
        migrations.DeleteModel(
            name='DiaHorario',
        ),
    ]
