# Generated by Django 2.1.4 on 2019-03-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20190327_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodohorario',
            name='dia',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default=1, max_length=9, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='periodohorario',
            name='fin',
            field=models.TimeField(auto_now_add=True, verbose_name='Cierre'),
        ),
        migrations.AlterField(
            model_name='periodohorario',
            name='inicio',
            field=models.TimeField(auto_now_add=True, verbose_name='Apertura'),
        ),
    ]
