# Generated by Django 2.1.4 on 2019-03-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_auto_20190327_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodohorario',
            name='fin',
            field=models.TimeField(blank=True, verbose_name='Cierre'),
        ),
        migrations.AlterField(
            model_name='periodohorario',
            name='inicio',
            field=models.TimeField(blank=True, verbose_name='Apertura'),
        ),
    ]
