# Generated by Django 2.1.4 on 2019-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_auto_20190327_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodohorario',
            name='fin',
            field=models.TimeField(verbose_name='Cierre'),
        ),
        migrations.AlterField(
            model_name='periodohorario',
            name='inicio',
            field=models.TimeField(verbose_name='Apertura'),
        ),
    ]
